### PR TITLE
--version switch takes priority over default_command

### LINKED ISSUE #206: app --version should not invoke default_command
Dave,

I have an app with default command set to open up a shell from which other commands can be typed.

It's working fine, except that if I invoke 'app --version', I would expect the app to /not/ invoke the default command and simply report the version.  'app --help' works like this, just printing the help text without bringing up the shell afterwards.  Seems 'app --version' should work the same way.

### PR DESCRIPTION
**Pull request by specious**
As mentioned in #206, --version switch should take priority over default_command.

### CODE REVIEW

**Comment by davetron5000** [comment]
Can you add a test for this?

**Comment by specious** [comment]
@davetron5000, I would love to.

I'm relatively new to Ruby and I don't feel like I'm sufficiently familiar with testing in this environment.  I looked at the Travis CI logs which clued me in that I should run:

```
bundle exec rake test features
```

That generated `results.html` which I enjoyed reading.  I scrolled through the code in `test/` and it looks like maybe tests for the functionality in question can be added to `test/tc_help.rb` since [the version switch is currently implemented as part of 'help' functionality](https://github.com/davetron5000/gli/blob/548b043b64e78298a5c5e176643183b88527713a/lib/gli/commands/help.rb#L74).

Any advice you could impart on me at this point would be of significant value.

**Comment by davetron5000** [comment]
Yeah, there's two bits of tests for this. `rake test` will run unit tests and `rake features` will run integration tests.  Those are specified using Cucumber (files in `features/`).  Since this affects the user interface of a generated app, you probably want to write an integration test.

If you are new to Ruby and especially if you haven't seen Cucumber, it's pretty gnarly.

You could also test this as a unit test as you describe.

**Comment by specious** [comment]
I added a feature test in `features/todo.feature`, which passes with the change made in 19eacdf9ee6d81918cc72600e42e23e03568e348 but not without.  For the record, the command to run the integration tests is:
```
bundle exec rake features
```
And not:
```
rake features
```

**Comment by specious** [comment]
@davetron5000, could you take another look at this?

**Comment by davetron5000** [comment]
So sorry to lose track of this.  It looks good.  Will merge and release today

**Pull request merged**
