### PR TITLE
Include the backtrace when printing the exception message.

### PR DESCRIPTION
**Pull request by annafw**
Minor update. I think the exception backtrace should be included by default with the exception message.

### CODE REVIEW

**Comment by davetron5000** [comment]
This feels kinda messy insomuch as you will get really large error messages with a lot of noise in them for even innocuous things.  Since GLI uses exceptions for argument parsing, if you omit a required flag (e.g.), you'll get a big stack trace.

Have you been using `GLI_DEBUG`?  This, if set, will cause the app to allow the exception to bubble up instead of being swallowed.

The idea being that "normally" your app and its error messages are sufficient for the user and you only need the backtrace for development or debugging.  Obviously, that's an assumption :)

What if we add a feature flag like `argument_handling_strategy`, maybe named `show_backtraces` or something.  Then your code works almost as-is, just wrap it behind an `if @show_backtraces`

**Comment by annafw** [comment]
I think that sounds good. 

To clarify - you're suggesting that if someone does this in their gli app, then the full backtrace would be shown:
arguments :show_backtraces
?

**Comment by davetron5000** [comment]
Sort-of, I guess a) is `GLI_DEBUG` not sufficient for your needs?  If "yes", then b) I would suggest adding a new method named `show_backtraces`:

```ruby
#!/usr/bin/env ruby
require 'gli'
require 'hacer'
 
include GLI::App
 
program_desc 'A simple todo list'

show_backtraces # <------

flag [:t,:tasklist], :default_value => File.join(ENV['HOME'],'.todolist')
 
pre do |global_options,command,options,args|
  $todo_list = Hacer::Todolist.new(global_options[:tasklist])
end
 
command :add do |c|
  c.action do |global_options,options,args|
    $todo_list.create(args)
  end
end
 
command :list do |c|
  c.action do
    $todo_list.list.each do |todo|
      printf("%5d - %s\n",todo.todo_id,todo.text)
    end
  end
end
 
command :done do |c|
  c.action do |global_options,options,args|
    id = args.shift.to_i
    $todo_list.list.each do |todo|
      $todo_list.complete(todo) if todo.todo_id == id
    end
  end
end
 
exit run(ARGV)
```

And you can implement it similar to how `argument_handling_strategy` is implemented, if that makes sense.

**Comment by annafw** [comment]
I had another case where I needed the backtrace, and I tried GLI_DEBUG=true, and that is sufficient for my needs. I'll close this pull request. Thanks!

**Comment by davetron5000** [comment]
Cool.  The best code is the code we don't have to write :)

**Pull request closed without merging**
