### PR TITLE
Use default terminal width when stty doesn't know (closes #222)

### LINKED ISSUE #222: Help output is too narrow when run in Emacs on Linux
When I run a gli program inside Emacs in Linux, the help output is too narrow.  To reproduce:

Create a new gli project

* Create a new gli program as shown in the README (`gli init todo list add complete`, etc.)
* Start emacs
* In Emacs, start a command shell (M-X shell)
* In the command shell, run the todo program:

```
wayne@treebeard:/tmp/todo$ bundle exec bin/todo
fatal: Not a git repository (or any of the parent directories): .git
NAME
    todo - Describe your application here

SYNOPSIS
    todo [global options] command [command options] [arguments...]

VERSION
    0.0.1

GLOBAL OPTIONS
    -f, --flagname=The name of the argument - Describe
                                              some
                                              flag
                                              here
                                              (default:
                                              the
                                              default)
    --help                                  - Show
                                              this
                                              message
    -s, --[no-]switch                       - Describe
                                              some
                                              switch
                                              here
    --version                               - Display
                                              the
                                              program
                                              version

COMMANDS
    add      - Describe
               add
               here
    complete - Describe
               complete
               here
    help     - Shows
               a
               list
               of
               commands
               or
               help
               for
               one
               command
    list     - Describe
               list
               here
```

# Versions

* gli 2.13.1
* Emacs 46.1
* Debian Linux, v. 8 ("Jessie")

# The stty command is the culprit

Run outside of emacs, the stty command reports its width normally:

    wayne@treebeard:~$ stty size
    63 237

But inside an Emacs shell, it reports the width like this:

    wayne@treebeard:~$ stty size
    0 0

I presume that "0 0" means that stty can't determine the terminal size.  I haven't found out if this represents a bug, or is just the way it is in an Emacs shell.

# A possible workaround

It should be possible to make gli to disregard a zero width report from stty, causing it to fallback to `Terminal.default_size`.  That will result in passable output when a gli program is run in emacs, or any other environment where stty doesn't know the terminal width.

If you like, I'd be glad to submit a pull request with that change.

### PR DESCRIPTION
**Pull request by wconrad**

### CODE REVIEW

**Comment by wconrad** [comment]
The test failures on travis-ci are the same ones I get when I run the tests locally, with or without this pull request.

**Comment by davetron5000** [comment]
I'll look into them.  This PR looks good.  I do think your suggestions for a larger redesign would result in better code, but this feels less risky as it is a smaller change.

**Comment by wconrad** [comment]
Thanks for looking at it.  Yes, lower risk is exactly what I was after.

**Comment by davetron5000** [comment]
Can you merge master into this and see if that fixes the build?

**Comment by wconrad** [comment]
There's a force push for you.  The build works now.  There's a deprecation warning from rspec, but that can be dealt with separately:

```
ruby -v: ruby 2.1.6p336 (2015-04-13 revision 50298) [x86_64-linux]
...DEPRECATION: Using `should` from rspec-expectations' old `:should` syntax without explicitly enabling the syntax is deprecated. Use the new `:expect` syntax or explicitly enable `:should` with `config.expect_with(:rspec) { |c| c.syntax = :should }` instead. Called from /home/wayne/.rvm/gems/ruby-2.1.6@gli-dev/gems/aruba-0.5.1/lib/aruba/api.rb:239:in `assert_exit_status'.
.............................................................................................................................................................................................................................................................................................................................................................................................................................................................
```

**Comment by davetron5000** [comment]
Added a test case (which failed before your patch).  Gonna merge a few more PRs and release this soon.  Thanks for doing this!

**Comment by davetron5000** [comment]
Other PRs weren't ready, so this is now released as 2.13.2.

**Comment by wconrad** [comment]
Outstanding... thanks for the test and the merge.

**Pull request merged**
