### PR TITLE
Basic implementation of :multiple option for flags

### LINKED ISSUE #240: Allow multiple flags of the same type
I'd like to be able to use the same flag more than once in a command, like in Postgres's `pg_dump` command:

`pg_dump --table users --table events`

Ideally there would be some sort of `:multiple` option that turns these arguments into an array. Note that this is different from an argument that accepts multiple values. Thoughts?

### PR DESCRIPTION
**Pull request by JacobEvelyn**
Note that this commit does not include any tests of this functionality.

Resolves #240

### CODE REVIEW

**Comment by davetron5000** [comment]
Implementation looks good and is backwards-compatible.  Should (hopefully) be easy to test?

**Comment by JacobEvelyn** [comment]
Let me know if there are other test cases I missed!

**Comment by davetron5000** [comment]
Nice!  When I get to my laptop tomorrow I'll give it a final look and then merge/release.

**Comment by JacobEvelyn** [comment]
Perfect, thanks!

**Comment by davetron5000** [comment]
This is now released in version 2.14

Thanks again!

**Pull request merged**
