### PR TITLE
Respect autocomplete setting when parsing subcommands

### PR DESCRIPTION
**Pull request by atareshawty**
In response to #287 

The first commit adds tests to demonstrate what (I _think_) the expected behavior should be:

- In loose mode with autocomplete = false, the parser doesn't attempt to autocomplete the sub command
  - Instead, the partial subcommand ends up as an argument to the parent command
- In strict mode with autocomplete = true, the parser raises an error with the message: `error: Too many arguments for command`

I'm starting the PR as a draft because I'm not 100% sure if I'm correctly stating the expected behavior.

The next commit fixes the issue and makes the tests pass 🚀

### CODE REVIEW

**Comment by davetron5000** [comment]
Nice catch on the strict arg handling. Your overall approach looks good.

**Comment by atareshawty** [comment]
Thanks! This is ready for review then 😄

**Comment by davetron5000** [comment]
OK, cool.  A couple of questions just to make sure I'm following it:

1. Looks like the bug was that the autocomplete configuration was not properly being passed down when recursively finding commands, so the system defaulted to the wrong thing?
2. Did you check this against your app to make sure it does work? The integration testing in this repo isn't very good or I'd have encouraged you to write one, but I don't think it's necessary since you ahve a good unit test and you checked it locally

**Comment by atareshawty** [comment]
> Looks like the bug was that the autocomplete configuration was not properly being passed down when recursively finding commands, so the system defaulted to the wrong thing?

Correct.

> Did you check this against your app to make sure it does work?

**Comment by atareshawty** [comment]
Here is an example when using the patched version: https://github.com/Root-App/gli-auto-complete/tree/verify-fix. I've updated the README to include how the output changes with the patch

**Comment by davetron5000** [comment]
OK, awesome.  I will merge and release here in a few…

**Comment by davetron5000** [comment]
Released just now as 2.18.1

Thanks again for the fix!

**Comment by atareshawty** [comment]
No problem! Thank you for maintaining this great gem

**Pull request merged**
